### ISSUE TITLE
Questions and feedback

### ISSUE THREAD

**Issue by MikaelElkiaer** [mrjosh/helm-ls#17]
Hi, first off, awesome work on this!

It is super useful in its current state, and I only really miss few things:

- go-to/peek definition - i. e. being able to hover (`K`) or `vim.lsp.buf.definition()`
- running alongside yaml LSP - not sure how this is possible (I guess the yaml needs to be stripped), however, what I hope to achieve is yaml schema validation
- extra: perhaps https://github.com/ngalaiko/tree-sitter-go-template can be adopted for better syntax highlighting

A question though, do you have a wishlist or set of features already?

Edit: Trying not to mix up LSP and TS

**Comment by qvalentin** [comment]
I guess we can close this by now. If you have any other feature suggestions feel free to open another issue.

For syntax highlighting: https://github.com/ngalaiko/tree-sitter-go-template/pull/13 is looking promising.
