### ISSUE TITLE
Publish a release

### ISSUE THREAD

**Issue by varac** [mrjosh/helm-ls#18]
Please do a release - it helps ppl using GH package managers to properly install it without browsing the release page.
I know it's still in development
 Thx !

**Comment by hinricht** [comment]
Also needed for eget:

```
$ eget mrjosh/helm-ls
404 Not Found (URL: https://api.github.com/repos/mrjosh/helm-ls/releases/latest)
```

**Comment by mrjosh** [comment]
Hi.
Sorry for the late response, i've been busy lately and couldn't focus on this project
First ever release has been published
Hope this helps you to install helm-ls easily 
https://github.com/mrjosh/helm-ls/releases/latest
Thank you

**Comment by varac** [comment]
@mrjosh thanks !!
