### ISSUE TITLE
Client 1 quit with exit code 2 and signal 0

### ISSUE THREAD

**Issue by varac** [mrjosh/helm-ls#19]
Hi, first of all, thanks for this awesome ls ! I've been struggling for a while now with proper chart template validation.

It works nicely, but I noticed that it produces this error msg after closing nvim:
```
❯ vi deployment.yaml
Client 1 quit with exit code 2 and signal 0
```

Here's the relevant output from /home/varac/.cache/nvim/lsp.log, see the last two lines:

```
[START][2022-11-23 10:04:43] LSP logging initiated
[START][2022-11-23 10:04:47] LSP logging initiated
[ERROR][2022-11-23 10:04:47] .../vim/lsp/rpc.lua:420	"rpc"	"helm_ls"	"stderr"	'{"level":"info","msg":"helm-lint-langserver: connections opened","time":"2022-11-23T10:04:47+01:00"}\n'
[ERROR][2022-11-23 10:04:47] .../vim/lsp/rpc.lua:420	"rpc"	"helm_ls"	"stderr"	'{"level":"info","msg":"/home/varac/projects/containers/kubernetes/helm/charts/varac/helmcharts/personal-gitlab-exporter","time":"2022-11-23T10:04:47+01:00"}\n'
[ERROR][2022-11-23 10:04:47] .../vim/lsp/rpc.lua:420	"rpc"	"helm_ls"	"stderr"	'{"level":"info","msg":"/home/varac/projects/containers/kubernetes/helm/charts/varac/helmcharts/personal-gitlab-exporter/values.yaml file loaded successfully","time":"2022-11-23T10:04:47+01:00"}\n'
[ERROR][2022-11-23 10:04:47] .../vim/lsp/rpc.lua:420	"rpc"	"helm_ls"	"stderr"	'{"level":"info","msg":"helm lint: result: []","time":"2022-11-23T10:04:47+01:00"}\n'

[ERROR][2022-11-23 10:04:49] .../vim/lsp/rpc.lua:420	"rpc"	"helm_ls"	"stderr"	'panic: request "shutdown" was never replied to\n\ngoroutine 10 [running]:\n'
[ERROR][2022-11-23 10:04:49] .../vim/lsp/rpc.lua:420	"rpc"	"helm_ls"	"stderr"	"go.lsp.dev/jsonrpc2.ReplyHandler.func1({0x17ec1d8, 0xc0001ae000}, 0xc00034a460, {0x7f6544163958?, 0xc000624080?})\n\t/home/runner/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:44 +0x165\ngo.lsp.dev/jsonrpc2.(*conn).run(0xc0004faa50, {0x17ec1d8, 0xc0001ae000}, 0xc000287df0)\n\t/home/runner/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/conn.go:206 +0x24b\ncreated by go.lsp.dev/jsonrpc2.(*conn).Go\n\t/home/runner/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/conn.go:189 +0xb0\n"
```

Here's a minmal config to reproduce (same as I used for https://github.com/neovim/nvim-lspconfig/issues/2252):

<details>
  <summary>Click me</summary>
  local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'towolf/vim-helm',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

local load_config = function()
  vim.lsp.set_log_level 'trace'
  require('vim.lsp.log').set_format_func(vim.inspect)
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
    vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
    vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
    vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
  end

  vim.api.nvim_create_autocmd({'BufNewFile', 'BufRead'} , {
    pattern = '*/templates/*.yaml,*/templates/*.tpl,*.gotmpl,helmfile*.yaml',
    -- pattern = 'deployment.yaml',
    callback = function()
      vim.opt_local.filetype = 'helm'
    end
  })

  -- Add the server that troubles you here

  -- https://github.com/mrjosh/helm-ls#nvim-lspconfig-setup

  local configs = require('lspconfig.configs')
  local util = require('lspconfig.util')

  if not configs.helm_ls then
    configs.helm_ls = {
      default_config = {
        cmd = {"helm_ls", "serve"},
        filetypes = {'helm'},
        root_dir = function(fname)
          return util.root_pattern('Chart.yaml')(fname)
        end,
      },
    }
  end
  local lsp = require('lspconfig')
  lsp.helm_ls.setup {
    filetypes = {"helm"},
    cmd = {"helm_ls", "serve"},
  }

  lsp.yamlls.setup{
    -- on_attach = on_attach,
    -- -- filetypes = { "yaml", "yaml.docker-compose" },
    -- filetypes = { "yaml.docker-compose" },
    -- flags = lsp_flags,
    -- capabilities = capabilities,
    -- settings = {
    --   yaml = {
    --     completion =  true,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  local packer_group = vim.api.nvim_create_augroup('Packer', { clear = true })
  vim.api.nvim_create_autocmd(
    'User',
    { pattern = 'PackerComplete', callback = load_config, group = packer_group, once = true }
  )
else
  load_plugins()
  require('packer').sync()
  load_config()
end

</details>

**Comment by mrjosh** [comment]
Hi, Hope this message finds you well
Sorry for late response, I've been busy lately and couldn't work on this project
This error got fix on this version
https://github.com/mrjosh/helm-ls/releases/tag/v0.0.2
