### ISSUE TITLE
Config help

### ISSUE THREAD

**Issue by goof03** [mrjosh/helm-ls#29]
Hi i try to setup helm-ls and yamlls in a LazyVim. But i cant get it working. helm filetype is not recognize and if i had yaml it's a mess with yamlls. 
Don't really understand all this LSP stuff, I need help please

**Comment by mrjosh** [comment]
Is your issue solved with the vim-helm plugin? @goof03

**Comment by Mo0rBy** [comment]
Hey @mrjosh I'm not sure if I should open a new issue or use this one, as I'm in the same boat as OP.

I have yamlls and helmls setup, I have the `vim-helm` plugin installed and it looks like both LSP's attach to Helm chart files, but I get an absolute mess of yamlls errors.

The best thing I can do is just add some code to my LSP config to disable Diagnostics on `helm` filetypes, but I obviously want to get helmls working as it should.

If you want me to open a new issue, let me know and I'll do it. My nvim config is in a public repo if you want to take a look at my LSP configuration for disabling the Diagnostics.

**Comment by qvalentin** [comment]
Hi @Mo0rBy, please check out https://github.com/mrjosh/helm-ls/issues/44 and also the minimal config in the examples directory.
