### ISSUE TITLE
Missing DLLs on Windows

### ISSUE THREAD

**Issue by fnuttens** [mrjosh/helm-ls#68]
The LSP needs the following at launch:
- `libstdc++-6.dll`
- `libgcc_s_seh-1.dll`

**Comment by qvalentin** [comment]
Hi, thanks for reporting this. Can you please elaborate how you can fix this or what a user needs to do when installing the lsp? Maybe open op a PR to the readme?

**Comment by fnuttens** [comment]
I guess a quick fix is for the user to copy the missing DLLs inside the bin folder, but I don’t have access to a Windows machine ATM so I can’t test for now.

A transparent solution for the user would be to add the DLLs as static libraries to your binary, but I have no idea how to do that in a Go project.

**Comment by qvalentin** [comment]
Seems like this was caused by using the yaml tree-sitter-parser, that uses a c++ scanner. The parser was not really used for anything so I removed it for now.
