### ISSUE TITLE
Possible to make it work with CoC (neovim) ?

### ISSUE THREAD

**Issue by metal3d** [mrjosh/helm-ls#75]
Hello, 

CoC is a very nice plugin that can use Langauge Servers (it works very well with Go, Python, TypeScript... and so on)

I try to make `helm_ls` working, but nothing seems to work.

Here is the configuration I added to CocConfig:

```json
  "languageserver": {
    "helm": {
      "command": "helm_ls",
      "filetypes": ["yaml"]
    }
  },

```

I also tried:

```json
  "languageserver": {
    "helm": {
      "command": "helm_ls",
      "argd": ["serve"],
      "filetypes": ["yaml"]
    }
  },

```

The server seems to be never used, never started, and I've got no diagnostic with helm files.

If someone can help...

**Comment by metal3d** [comment]
Ho!

Found:

```json
  "languageserver": {
    "helm": {
      "command": "helm_ls",
      "args": ["serve"],
      "filetypes": ["yaml", "helm", "helmfile"],
      "rootPatterns": ["Chart.yaml"]
    }
  },
```

And it's OK. It's fantastic, I've got errors, documentation, ...

![image](https://github.com/mrjosh/helm-ls/assets/100080/358eb169-158a-41bb-bf02-87ee064c27d3)


![image](https://github.com/mrjosh/helm-ls/assets/100080/5c2e8abc-adba-42f1-875e-4a81c3e90910)

![image](https://github.com/mrjosh/helm-ls/assets/100080/39d19637-e731-4e34-ac84-1fbeb5ca2556)


Maybe I can make a PR with the "how to neovim + CoC" in the README?

**Comment by qvalentin** [comment]
Fixed in https://github.com/mrjosh/helm-ls/pull/79
